development:
  adapter: postgis
  database: truck_tracking_development
  host: localhost
  pool: 5
  timeout: 5000
  schema_search_path: public, postgis
  username: postgres
  password: 

test:
  adapter: postgis
  database: truck_tracking_test
  pool: 5
  timeout: 5000
  schema_search_path: public, postgis
  username: postgres
  password: 

production:
  adapter: postgis
  database: truck_tracking_production
  pool: 10
  timeout: 5000
  schema_search_path: public, postgis
  username: postgres
  password: 
  port: 5432


